baseurl: "https://javaswag.github.io"
title: "Javaswag"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
pagination:
  pagerSize: 100
uglyURLs: false
metaDataFormat: "yaml"
LanguageCode: ru
params:
  telegram: https://t.me/javaswag
  itunes: https://podcasts.apple.com/podcast/id1498075914
  android: https://music.youtube.com/channel/UCz5KcC6lqP3m3QyrFH_DOKQ
  spotify: https://open.spotify.com/show/5F6u4mQeATuLvZ60WoanTi
  yandex: https://music.yandex.ru/album/10870021
  castbox: https://castbox.fm/channel/javaswag-id2626600
  vk: https://vk.com/podcasts-126637725
  podcast: https://pc.st/1498075914
  feed: /index.xml
  feedDraft: /draft/index.xml
  s3Stats: https://javaswag-logs.website.yandexcloud.net/
  desc: Подкаст о разработке на Java. Все то, о чем вы боялись спросить в кулуарах.
  summary: Подкаст о разработке на Java
  StaticURL: "https://javaswag.github.io"
  LanguageCode: ru
  Keywords: technology,java,jvm
  yandexS3: "https://storage.yandexcloud.net/javaswag/"
  title: javaswag
  mainTitle: "Подкаст о разработке на Java"
  subTitle: "Все то, о чем вы боялись спросить в кулуарах."
  image: images/logo.png
  imageDraft: img/logo-draft.png
  author: Dima V
  itunesAuthor: javaswag
  itunesName: javaswag
  authorEmail: volyihin@yandex.ru
  twitter: https://twitter.com/javaswagpodcast
  twitterName: javaswagpodcast
permalinks:
  post: "/:title"
